### ISSUE TITLE
systemd issue, converge failed

### ISSUE THREAD

**Issue by illia-sh** [anuriq/chef-kibana5#18]
```
  * kibana5_configure[kibana] action configure

           ================================================================================
           Error executing action `configure` on resource 'kibana5_configure[kibana]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `Kibana Backend' for Custom resource systemd_service from cookbook systemd

System Info:
           ------------
           chef_version=13.2.20
           platform=ubuntu
           platform_version=16.04
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
           program_name=chef-client worker: ppid=1741;start=16:29:07;
           executable=/opt/chef/bin/chef-client

```

I haven't checked yet , 
but systemd cookbook was updated recently , so it might be the root cause.
https://github.com/nathwill/chef-systemd/releases

**Comment by illia-sh** [comment]
I have pinned   cookbook 'systemd', "= 2.1.3"  in Berksfile , now works fine.

**Comment by anuriq** [comment]
also it should be fixed in 3.0.2

**Comment by randyrue** [comment]
I'm having what might be a similar problem but berks says I'm running systemd 3.1.0
`   kibana5_configure[kibana] action configure

    Error executing action `configure` on resource 'kibana5_configure[kibana]'

    NoMethodError
    -------------
    undefined method `description' for Custom resource systemd_service from cookbook systemd

System Info:
    ------------
    chef_version=13.2.20
    platform=opensuseleap
    platform_version=42.2
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-client worker: ppid=16842;start=14:09:40;
    executable=/opt/chef/bin/chef-client
`

Any guidance for a newbie?

- randy

**Comment by iancward** [comment]
I'm having the same issue with `description` property using version 3.1.0 of the systemd cookbook.
Pinning to systemd version `2.1.3` also fixed my issue.

**Comment by randyrue** [comment]
Added the line "cookbook 'systemd', "= 2.1.3"" to my Berksfile, am I doing that right?

Still getting:
NoMethodError: undefined method `description' for Custom resource systemd_service from cookbook systemd

**Comment by anuriq** [comment]
Hi all.
I fixed version in a cookbook for now. Author of `systemd` cookbook have fully refactored it. Better wait and see what will happen.

**Comment by mburns** [comment]
This appears fixed in more recent 3.x versions of systemd (at least, I can't reproduce it anymore) and the `2.1.3` version lock is an option for users with legacy support requirements.

Going to close this for now. Cheers!
